server.port=0
spring.kafka.consumer.bootstrap-servers=localhost:9092,localhost:9094

# unique consumer group id (for consumers to work in parallel while reading topics messages)
spring.kafka.consumer.group-id=product-created-events
# specifies which packages are trusted for JSON deserialization (safety config)
spring.kafka.consumer.properties.spring.json.trusted.packages=com.learn.self.kafka.product.core

# embedded db settings
spring.datasource.username=test
spring.datasource.password=test
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.kafka.consumer.auto-offset-reset=latest